spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  #autoconfigure:
  #  exclude:
  #    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: default
  mongodb:
    host: localhost
    port: 27017
    database: taskdb

---
spring:
  config:
    activate:
      on-profile: docker
  mongodb:
    host: ${SPRING_DATA_MONGODB_HOST:mongodb}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    database: ${SPRING_DATA_MONGODB_DATABASE:taskdb}
    username: ${SPRING_DATA_MONGODB_USERNAME:admin}
    password: ${SPRING_DATA_MONGODB_PASSWORD:admin123}
    authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}